Feat/improve time progression testing explanations
sfeir-open-source/sfeir-school-rxjs pull request #17
Opened 2023-04-11 21:22 UTC by lou-theo

### Problème rencontré

Lorsque j'ai fait la school j'ai eu un gros point de blocage avec les TestScheduler, je ne comprenais notamment pas du tout le pourquoi de mettre 999ms plutôt que 1s. A mes yeux ce point mérite plus d'attention.
Pour cela je propose l'ajout d'une nouvelle slide avec citations de la doc (actuellement cela prend surement un peu trop de place, il faudrait voir pour rétrécir & rendre cela plus lisible)

Je propose également de s'attarder sur la temporalité des marbles lors de l'explication de chacun, en faisant bien attention à comprendre pour chaque cas quelle est la frame à laquelle chaque event est émis ou autre (error, complete...)

### Bonus: amélioration des tests

Lorsque j'exécutais les tests j'avais un peu de mal à comprendre pourquoi ils étaient si long: cela était du au fait que plusieurs observables étaient souscrits en dehors du TestSheduler et donc en temps d'execution réel.
J'ai donc ajouté le TestSheduler dans tous les cas avec un beforeEach, permettant de passer de temps d'exécutions d'environ 12sec à 3sec

2023-04-18 06:21 UTC, kuroidoruido commented
Chez moi ça ne fonctionne pas (j'ai clone ta branche sur ton fork, j'ai juste npm i et lancé la solution du lab 6) :

```
❯ npm run start:06:solution

> common@1.0.0 start:06:solution
> jest ./06-tests-solution

ts-jest[config] (WARN) message TS151001: If you have issues related to imports, you should consider setting `esModuleInterop` to `true` in your TypeScript configuration file (usually `tsconfig.json`). See https://blogs.msdn.microsoft.com/typescript/2018/01/31/announcing-typescript-2-7/#easier-ecmascript-module-interoperability for more information.
ts-jest[config] (WARN) message TS151001: If you have issues related to imports, you should consider setting `esModuleInterop` to `true` in your TypeScript configuration file (usually `tsconfig.json`). See https://blogs.msdn.microsoft.com/typescript/2018/01/31/announcing-typescript-2-7/#easier-ecmascript-module-interoperability for more information.
 PASS  06-tests-solution/apple.service.spec.ts (25.698 s)
 FAIL  06-tests-solution/baking.service.spec.ts (25.749 s)
  ● BakingService › bakeCompote › should emit an apple every second

    expect(received).toEqual(expected) // deep equality

    - Expected  - 2
    + Received  + 2

    @@ -1,16 +1,16 @@
      Array [
        Object {
    -     "frame": 5000,
    +     "frame": 2000,
          "notification": Object {
            "error": undefined,
            "kind": "N",
            "value": "c",
          },
        },
        Object {
    -     "frame": 5000,
    +     "frame": 2000,
          "notification": Object {
            "error": undefined,
            "kind": "C",
            "value": undefined,
          },

       7 | beforeEach(() => {
       8 |   testScheduler = new TestScheduler((actual, expected) => {
    >  9 |     expect(actual).toEqual(expected);
         |                    ^
      10 |   });
      11 | });
      12 |

      at TestScheduler.assertDeepEqual (06-tests-solution/baking.service.spec.ts:9:20)
      at node_modules/rxjs/src/internal/testing/TestScheduler.ts:217:14
          at Array.filter (<anonymous>)
      at TestScheduler.Object.<anonymous>.TestScheduler.flush (node_modules/rxjs/src/internal/testing/TestScheduler.ts:215:39)
      at TestScheduler.Object.<anonymous>.TestScheduler.run (node_modules/rxjs/src/internal/testing/TestScheduler.ts:679:12)
      at Object.<anonymous> (06-tests-solution/baking.service.spec.ts:51:21)

  ● BakingService › bakeApplePie › should return an apple pie

    TypeError: Cannot read properties of null (reading 'subscribe')

      63 |       const appleSlices = new Array(64).fill(null).map((): AppleSlice => ({ _type: 'AppleSlice' }));
      64 |       testScheduler.run(() => {
    > 65 |         BakingService.bakeApplePie(pastry, compote, appleSlices).subscribe((pie) => {
         |                                                                 ^
      66 |           expect(pie._type).toBe('ApplePie');
      67 |           done();
      68 |         });

      at 06-tests-solution/baking.service.spec.ts:65:65
      at TestScheduler.Object.<anonymous>.TestScheduler.run (node_modules/rxjs/src/internal/testing/TestScheduler.ts:678:19)
      at Object.<anonymous> (06-tests-solution/baking.service.spec.ts:64:21)

  ● BakingService › bakeApplePie › should emit an error when not enough apples slices are given

    TypeError: Cannot read properties of null (reading 'subscribe')

      75 |       const appleSlices = new Array(63).fill(null).map((): AppleSlice => ({ _type: 'AppleSlice' }));
      76 |       testScheduler.run(() => {
    > 77 |         BakingService.bakeApplePie(pastry, compote, appleSlices).subscribe({
         |                                                                 ^
      78 |           next() {
      79 |             fail('should not emit a Compote');
      80 |           },

      at 06-tests-solution/baking.service.spec.ts:77:65
      at TestScheduler.Object.<anonymous>.TestScheduler.run (node_modules/rxjs/src/internal/testing/TestScheduler.ts:678:19)
      at Object.<anonymous> (06-tests-solution/baking.service.spec.ts:76:21)

  ● BakingService › bakeApplePie › should emit an error when not pastry are present in the plate

    TypeError: Cannot read properties of null (reading 'subscribe')

      91 |       const appleSlices = new Array(64).fill(null).map((): AppleSlice => ({ _type: 'AppleSlice' }));
      92 |       testScheduler.run(() => {
    > 93 |         BakingService.bakeApplePie(pastry, compote, appleSlices).subscribe({
         |                                                                 ^
      94 |           next() {
      95 |             fail('should not emit a Compote');
      96 |           },

      at 06-tests-solution/baking.service.spec.ts:93:65
      at TestScheduler.Object.<anonymous>.TestScheduler.run (node_modules/rxjs/src/internal/testing/TestScheduler.ts:678:19)
      at Object.<anonymous> (06-tests-solution/baking.service.spec.ts:92:21)

  ● BakingService › bakeApplePie › should emit an apple every second

    TypeError: Cannot read properties of null (reading 'pipe')

      107 |       const appleSlices = new Array(64).fill(null).map((): AppleSlice => ({ _type: 'AppleSlice' }));
      108 |       testScheduler.run(({ expectObservable }) => {
    > 109 |         const actual$ = BakingService.bakeApplePie(pastry, compote, appleSlices).pipe(map(() => 'p'));
          |                                                                                 ^
      110 |         const expected = '5s (p|)';
      111 |         expectObservable(actual$).toBe(expected);
      112 |       });

      at 06-tests-solution/baking.service.spec.ts:109:81
      at TestScheduler.Object.<anonymous>.TestScheduler.run (node_modules/rxjs/src/internal/testing/TestScheduler.ts:678:19)
      at Object.<anonymous> (06-tests-solution/baking.service.spec.ts:108:21)

Test Suites: 1 failed, 1 passed, 2 total
Tests:       5 failed, 4 passed, 9 total
Snapshots:   0 total
Time:        25.995 s
Ran all test suites matching /.\/06-tests-solution/i

```

2023-04-18 06:24 UTC, kuroidoruido requested changes

2023-04-18 06:24 UTC, kuroidoruido commented on steps/06-tests-solution/baking.service.spec.ts
>  import { BakingService } from '../common';
besoin de rebase main avant de merge, sinon ça ne fonctionne pas

2023-04-18 06:30 UTC, kuroidoruido requested changes

2023-04-18 06:30 UTC, kuroidoruido commented on docs/markdown/06-tests/03-tester-le-temps.md
> +<blockquote>
```suggestion

[Lien vers la documentation](https://rxjs.dev/guide/testing/marble-testing#time-progression-syntax)

# Point d'attention : progression du temps

<blockquote>
```

Faut couper en deux, sinon la slide est trop lourde et y'a trop de texte personne ne va écouter

2023-04-18 06:30 UTC, kuroidoruido commented on docs/markdown/06-tests/03-tester-le-temps.md
> +# Point d'attention: progression du temps
```suggestion
# Point d'attention : progression du temps
```

2023-04-18 06:30 UTC, kuroidoruido commented on steps/06-tests-solution/baking.service.spec.ts
> +});
normalement faut pas mettre de beforeEach à l'extérieur du describe de premier niveau. Sinon là tu définis un beforeEach global sur l'ensemble des tests de tout le projet

Donc soit faut virer le beforeEach et mettre directement l'affectation du new TestScheduler au top level. Soit bouger le beforeEach à l'intérieur du describe()

2023-04-18 06:30 UTC, kuroidoruido commented on steps/06-tests-solution/apple.service.spec.ts
> +});
normalement faut pas mettre de beforeEach à l'extérieur du describe de premier niveau. Sinon là tu définis un beforeEach global sur l'ensemble des tests de tout le projet

Donc soit faut virer le beforeEach et mettre directement l'affectation du new TestScheduler au top level. Soit bouger le beforeEach à l'intérieur du describe()

2023-04-19 11:52 UTC, lou-theo commented on steps/06-tests-solution/baking.service.spec.ts
> +});
Effectivement, j'avais zappé ça
On en peut pas mettre just eune instanciation du TestScheduler en top level à çacesu de ça https://github.com/ReactiveX/rxjs/issues/2757#issuecomment-316064350

2023-04-24 07:40 UTC, merged