WIP: Rework exercises
sfeir-open-source/sfeir-school-rxjs pull request #8
Opened 2020-08-10 09:47 UTC by mtroysi

Resolves #5 

This pull request is adding a step-by-step exercise which leads to the construction of a chatting application throughout the formation using observables.

The first exercise consists of creating basic observables using the constructor `new Observable(susbcriber => ...)` and subscribe to theses observables in order to get familiarized with the flow.
In the second exercise, observables will be created using `fromEvent` to detect a keypress on the `Enter` key to submit data.
In the third exercise, we add operators to create an anti-spamming feature.

The application is made with React but most of the React logic is already written so that the exercises can focus on RxJS. The participants will only have to work in two files : `App.js` and `Username.jsx`.
The idea is for the formator to start the server on his computer, start ngrok and give the generated URL to the participants so they can all chat on the same server.

Although theses exercises might be more playful than the current exercises, they are far less complex (particularly concerning the combination of operators) and the idea is to combine both.

The issue #5 suggests to move the current exercises at the end of the formation, however they are currently well integrated with the order of the chapters and it would not make sense to put them all at the end. Moreover, the chatting application needs the notions of Rx Observables and subscribers which come late in the formation.
For now, I have put the chat exercises in the chapters in which I thought they fitted the most but I have let the previous exercises at the same place. Do you have any suggestions concerning the matter ?

At the time, exercises concerning scheduler and marble testing are still missing.

Let me know if you have any comment regarding the exercises or any improvements that can be made.

2020-08-11 08:10 UTC, Xartok commented on docs/markdown/observable/observable.md
> +3. Do the same for the events 'refresh-users' and 'new message' that respectively update the online users and update the displayed messages
l'évenement est `new-message`

2020-08-11 08:17 UTC, Xartok commented on exercises/react-chat/step01_solution/App.js
> +  }, [messages])
il me semble qu'en mettant `messages` en dépendance, à chaque nouveau message la souscription va être refaite, vu qu'on change `messages` avec le `setMessages`

2020-08-11 08:22 UTC, Xartok commented on exercises/react-chat/src/Messages.jsx
> +    const container = document.getElementById('messages-container')
il vaudrait mieux utiliser une ref ici

2020-08-25 09:44 UTC, jefBinomed requested changes
Il faut retravailler la façon de jouer l'exercice pour essayer de  faire en sorte que le participant n'ai pas à lancer plusieurs lignes de commandes. Utiliser par exemple un parallel-shell ou autre. 

De plus, il faut rajouter le readme des exos de chat react.

2020-08-25 09:44 UTC, jefBinomed commented on exercises/react-chat/step01_solution/App.js
> +const observable = new Observable(subscriber => {
c'est tout bete mais dans le code sample fourni à la base, l'observable s'apelle messagesObservable. Son nom était assez parlant. Il faudrait mieux que les solutions aient le même nom ?

2020-08-25 09:44 UTC, jefBinomed commented on docs/markdown/observable/observable.md
> +3. Do the same for the events 'refresh-users' and 'new message' that respectively update the online users and update the displayed messages
il faut aussi rajouter un readme dans le répertoire react-chat afin de remettre les consignes de l'exercice avec les helpers de code nécessaire.

Je rajouterais aussi (dans le readme et dans le slide) comment démarrer l'exercice

2020-08-25 09:44 UTC, jefBinomed commented on exercises/react-chat/src/App.js
> +  useEffect(() => {
pour le bien de l'exercice (et ce de façon indépendante des commentaires), J'aurais mis des fonctionnées nommées sur tes useEffect du genre 

```
useEffect(subscriptionToMessage)

const subscriptionToMessage = () => {
    // subscribe to users
    // and don't forget to unsubscribe !
}

```

2020-08-25 09:44 UTC, jefBinomed commented on exercises/react-chat/src/App.js
> +    // subscribe to messages
Il faudrait aussi surement ajouté dès le code ici le paramètre [messages] au use effect. Car si on est pas familier avec React et les hooks, on peut ne pas comprendre d'où sort le [messages] qui arrive dans la solution...

```
useEffect(subscriptionToMessage, [messages])

const subscriptionToMessage = () => {
    // subscribe to users
    // and don't forget to unsubscribe !
}
```

2020-08-25 09:44 UTC, jefBinomed commented on exercises/react-chat/src/App.js
> +    // and don't forget to unsubscribe !
comme c'est pas trivial la façon de se désynscrire, je préparerais le code dès l'exemple avec un truc comme ça : 

```
useEffect(subscriptionToMessage, [messages])

const subscriptionToMessage = () => {
    // subscribe to users
   return () => { 
      // and don't forget to unsubscribe here!
   }
}  
```

2020-08-25 09:44 UTC, jefBinomed commented on exercises/react-chat/src/helpers.js
> +export const getHeureMinutes = () => {
à remplacer par : 
à angliser ;) car le reste du code est en anglais

```
const hourTimeFormat = new Intl.DateTimeFormat('default', {hour24: true, hour: "numeric", minute: "numeric"});
export const getHeureMiutes = () => {
 return hourTimeFormat.format(new Date())
}
```

2020-08-25 09:44 UTC, jefBinomed commented on exercises/react-chat/step01_solution/App.js
> +    const subscription = usernameObservable.subscribe({
pourquoi ici tu as la méthode next ?

2020-08-25 09:44 UTC, jefBinomed commented on exercises/react-chat/step02_solution/App.js
> +    if (textInput.current) {
pourquoi on a ce controle ?

2020-08-25 09:44 UTC, jefBinomed commented on exercises/react-chat/step03_solution/App.js
> +        distinctUntilChanged(),
je suis pas sur de comprendre le distinct until changed et le filter sur le trim.

2020-08-25 10:43 UTC, kuroidoruido commented on exercises/react-chat/step01_solution/App.js
> +const observable = new Observable(subscriber => {
Perso je recommanderais plutôt de passer sur la convention RxJS qui est messsages$. Tout ce qui est observable termine par un dollar de sorte à être visible facilement

2020-08-25 13:26 UTC, jefBinomed commented on exercises/react-chat/step01_solution/App.js
> +const observable = new Observable(subscriber => {
oui bonne idée en effet :) je plusoie l'idée du $

2020-08-25 13:29 UTC, kuroidoruido commented on exercises/react-chat/step01_solution/App.js
> +const observable = new Observable(subscriber => {
Par contre si on passe là sur un dollar faut reprendre tout pour mettre des dollars. Si c'est gros peut-être une autre PR pour éviter que @mtroysi soit sur tous les fronts ;)

2020-08-26 06:36 UTC, Xartok commented on exercises/react-chat/step02_solution/App.js
> +    if (textInput.current) {
au premier chargement du composant (équivalent à componentDidMount) la ref est indéfinie, ensuite (équivalent à componentDidUpdate) elle est définie

2020-08-26 06:42 UTC, Xartok commented on exercises/react-chat/step03_solution/App.js
> +        distinctUntilChanged(),
distinctUntilChanged : si tu appuies sur entrée avec le même message ça ne le renvoie pas
filter: on n'envoie pas de message vide ou composé uniquement d'espace
par contre j'aurai mis le distinctUntilChanged après le filter pour qu'on ne puisse pas spammer juste en mettant un nombre différent d'espaces

2020-08-26 06:46 UTC, Xartok commented on exercises/react-chat/src/App.js
> +  useEffect(() => {
il vaut mieux mettre un verbe pour indiquer une action : subscribeToMessages

2020-08-31 12:19 UTC, mtroysi commented on exercises/react-chat/step01_solution/App.js
> +const observable = new Observable(subscriber => {
Je ne connaissais pas la convention mais effectivement je pense que ça fera gagner en lisibilité. Je peux changer ça dans la PR, ça ne me pose pas de problème et autant faire un truc propre directement ;)

2020-08-31 16:01 UTC, mtroysi commented on exercises/react-chat/step01_solution/App.js
> +    const subscription = usernameObservable.subscribe({
Ici je précise le callback next car j'ai aussi le callback error.
Dans les autres exemples, étant donné que je n'ai que le callback next, le callback que je donne est automatiquement attribué à next (les notifications error/complete sont alors ignorées)
Je pensais que c'était justement intéressant d'avoir les différentes notations avec notamment un cas d'erreur à gérer :)

2020-09-01 09:03 UTC, mtroysi commented on exercises/react-chat/src/Messages.jsx
> +    const container = document.getElementById('messages-container')
Ne fonctionne pas tel quel (on ne peut plus utiliser scrollTop et scrollHeight) ou alors tu avais une autre méthode en tête ?

2020-09-01 09:57 UTC, mtroysi commented on exercises/react-chat/step01_solution/App.js
> +  }, [messages])
C'est bien ce que je pensais, du coup j'ai testé d'autres options : 
- j'ai testé en mettant [] en dépendance (à priori la souscription n'a besoin d'être faite qu'une seule fois ?) mais à chaque message envoyé, celui-ci remplace le précédent
- en mettant pas de dépendances ça fonctionne, mais du coup la souscription est refaite à chaque render donc c'est pas fou non plus
Du coup je dois avouer que je ne comprends pas bien ce qui se passe ici et je me pose d'ailleurs la question pour les autres useEffect : 
- Pour users$ : je peux mettre [] et la mise à jour des utilisateurs en ligne se fait correctement (ici le serveur renvoie la liste complète des utlisateurs à chaque fois, il n'y a pas d'ajout dans le state)
- Pour username$ : je ne mets pas de dépendances, si je mets [] l'effet ne se joue qu'une seule fois et en cas d'une première saisie erronée, les autres saisies (même si elles sont correctes) n'auront pas d'effet (on reste sur l'écran d'erreur)
Si quelqu'un a une explication, ce comportement n'est pas très clair pour moi...

2020-09-01 13:57 UTC, kuroidoruido commented on exercises/react-chat/step01_solution/App.js
> +  }, [messages])
Pour messages je pense que vaut mieux laisser comme ça : le but c'est utiliser React pour montrer RxJS et pas faire le code React+RxJS le plus parfait. Y'a la logique, c'est pas parfait mais ça montre bien l'idée. Si on rend le truc optimal je sens qu'on va rentrer dans des compléxités côté React. Après c'est mon avis, ça se discute.

Pour les autres useEffect tu dois aussi unsubscribe() et subscribe à chaque render. C'est pas forcément très grave vu que c'est des observables, donc ça ne porte aucun comportement ni rien, c'est totalement lazy. Le plus important c'est qu'on ait jamais de subscribe qui ne serait pas unsubscribe et normalement ça n'arrivera pas ici :slightly_smiling_face:

2020-09-02 06:38 UTC, Xartok commented on exercises/react-chat/step01_solution/App.js
> +  }, [messages])
@mtroysi pour le useEffect qui s'occupe des messages: `message => setMessages([...messages, message])` fait une closure sur messages, c'est-à-dire que ca revient à faire `message => setMessages([...messagesAuMomentDuSubscribe, message])` à chaque subscribe, donc en mettant [] en dépendance, `message => setMessages([...[], message])`. C'est bien une complexité de React, il faut faire `message => setMessages(currentMessages => [...currentMessages, message])`.

2020-09-02 06:39 UTC, Xartok commented on exercises/react-chat/step01_solution/App.js
> +  }, [messages])
pour le useEffect qui s'occupe des users, pas de problème de ce genre.

2020-09-02 07:18 UTC, Xartok commented on exercises/react-chat/step01_solution/App.js
> +  }, [messages])
pour le useEffect qui s'occupe du username, dès qu'il y a une erreur le callback error est déclenché et l'observable est unsubscribed, c'est le comportement normal, et c'est pour ca que ca fonctionne si tu re-subscribe en ré-éxécutant le useEffect (en ne mettant pas de dépendance). Je suis d'accord sur le fait de ne pas trop s'appesantir sur les détails spécifiques à React, mais ici c'est un problème qu'il faudrait aussi gérer en Vanilla JS : comment gérer les erreurs de ce type avec des websockets ? J'ai essayé quelque chose [ici](https://stackblitz.com/edit/rxjs-playground-test-ynkl3i?devtoolsheight=33&file=index.ts) avec l'opérateur [retryWhen](https://www.learnrxjs.io/learn-rxjs/operators/error_handling/retrywhen)

2020-09-02 09:08 UTC, mtroysi commented on exercises/react-chat/step01_solution/App.js
> +  }, [messages])
@Xartok Merci pour l'explication ! Par contre pas tout compris pour le retryWhen, faudrait qu'on arrive à se capter :)

2020-09-14 17:14 UTC, kuroidoruido approved these changes

2020-09-16 15:11 UTC, jefBinomed commented
Il manque un exercice pour la partie sharable stream 

L'exercice 5 est marqué step 3 alors que c'est step 4.

Et je supprimerais le slide lazyness au début (après manipulate arrays)

2020-10-10 00:31 UTC, Xartok commented on exercises/react-chat/README.md
> +* Use `socket.on('event-name')` to listens to an event sent by the server
```suggestion
* Use `socket.on('event-name')` to listen to an event sent by the server
```

2020-10-10 00:31 UTC, Xartok commented on exercises/react-chat/README.md
> +* The server's reponse looks like this : `{ ok: boolean, username: "string" }` with `ok` being false when a username is already taken.
je ne comprends pas pourquoi boolean est écrit comme un type mais string comme une valeur, donc je fais cette suggestion, mais je vois que string est écrit comme une valeur à d’autres endroits, donc si j’ai vu juste il faudra changer partout.
```suggestion
* The server's response looks like this : `{ ok: boolean, username: string }` with `ok` being false when a username is already taken.
```

2020-10-10 00:31 UTC, Xartok commented on exercises/react-chat/README.md
> +2. In the function `susbscribeToUsers`, subscribe to the observable `users$` ans set the users list accordingly.
```suggestion
2. In the function `subscribeToUsers`, subscribe to the observable `users$` and set the user list accordingly.
```

2020-10-10 00:31 UTC, Xartok commented on exercises/react-chat/README.md
> +2. In the function `susbscribeToMessages`, subscribe to the observable `messages$` and add the new message to the message list.
```suggestion
2. In the function `subscribeToMessages`, subscribe to the observable `messages$` and add the new message to the message list.
```

2020-12-08 21:00 UTC, jefBinomed commented
reste l'exercice Stream

2020-12-08 21:00 UTC, jefBinomed commented
essayer de faire un rework de tchat react en vanilla ?

2020-12-17 20:42 UTC, kuroidoruido commented
@jefBinomed It seems something miss somewhere, when I make npm install or npm ci in docs/, I get this error :
```
⠼ snowpack installing... lit-html, sfeir-school-theme/dist/css/helper.css
✖ Package subpath './dist/css/helper.css' is not defined by "exports" in /home/anthony/SFEIR/sfeir-school-rxjs/docs/node_modules/sfeir-school-theme/package.json
```

2020-12-18 13:26 UTC, jefBinomed approved these changes

2020-12-18 13:27 UTC, merged